In [1]:
import numpy as np
import pandas as pd

In [2]:
churn = pd.read_csv('churn2_for tableau.csv')
churn.head()

Unnamed: 0  Churn  Tenure  City_Tier  CC_Contacted_LY      Payment  Gender  \
0           0      1     4.0        3.0              6.0   Debit Card  Female   
1           1      1     0.0        1.0              8.0          UPI    Male   
2           2      1     0.0        1.0             30.0   Debit Card    Male   
3           3      1     0.0        3.0             15.0   Debit Card    Male   
4           4      1     0.0        1.0             12.0  Credit Card    Male   

   Service_Score  Account_user_count account_segment  CC_Agent_Score  \
0            3.0                   3           Super             2.0   
1            3.0                   4       Regular +             3.0   
2            2.0                   4       Regular +             3.0   
3            2.0                   4           Super             5.0   
4            2.0                   3       Regular +             5.0   

  Marital_Status  rev_per_month  Complain_ly  rev_growth_yoy  \
0         Single            9.0          1.0            11.0   
1         Single            7.0          1.0            15.0   
2         Single            6.0          1.0            14.0   
3         Single            8.0          0.0            23.0   
4         Single            3.0          0.0            11.0   

   coupon_used_for_payment  Day_Since_CC_connect    cashback Login_device  
0                      1.0                   5.0  159.930000       Mobile  
1                      0.0                   0.0  120.900000       Mobile  
2                      0.0                   3.0  196.227799       Mobile  
3                      0.0                   3.0  134.070000       Mobile  
4                      1.0                   3.0  129.600000       Mobile

In [3]:
churn.drop('Unnamed: 0', axis=1, inplace=True)

In [4]:
churn.head()

Churn  Tenure  City_Tier  CC_Contacted_LY      Payment  Gender  \
0      1     4.0        3.0              6.0   Debit Card  Female   
1      1     0.0        1.0              8.0          UPI    Male   
2      1     0.0        1.0             30.0   Debit Card    Male   
3      1     0.0        3.0             15.0   Debit Card    Male   
4      1     0.0        1.0             12.0  Credit Card    Male   

   Service_Score  Account_user_count account_segment  CC_Agent_Score  \
0            3.0                   3           Super             2.0   
1            3.0                   4       Regular +             3.0   
2            2.0                   4       Regular +             3.0   
3            2.0                   4           Super             5.0   
4            2.0                   3       Regular +             5.0   

  Marital_Status  rev_per_month  Complain_ly  rev_growth_yoy  \
0         Single            9.0          1.0            11.0   
1         Single            7.0          1.0            15.0   
2         Single            6.0          1.0            14.0   
3         Single            8.0          0.0            23.0   
4         Single            3.0          0.0            11.0   

   coupon_used_for_payment  Day_Since_CC_connect    cashback Login_device  
0                      1.0                   5.0  159.930000       Mobile  
1                      0.0                   0.0  120.900000       Mobile  
2                      0.0                   3.0  196.227799       Mobile  
3                      0.0                   3.0  134.070000       Mobile  
4                      1.0                   3.0  129.600000       Mobile

In [5]:
churn.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11260 entries, 0 to 11259
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   Churn                    11260 non-null  int64  
 1   Tenure                   11260 non-null  float64
 2   City_Tier                11260 non-null  float64
 3   CC_Contacted_LY          11260 non-null  float64
 4   Payment                  11260 non-null  object 
 5   Gender                   11260 non-null  object 
 6   Service_Score            11260 non-null  float64
 7   Account_user_count       11260 non-null  int64  
 8   account_segment          11260 non-null  object 
 9   CC_Agent_Score           11260 non-null  float64
 10  Marital_Status           11260 non-null  object 
 11  rev_per_month            11260 non-null  float64
 12  Complain_ly              11260 non-null  float64
 13  rev_growth_yoy           11260 non-null  float64
 14  coupon_used_for_paymen

In [6]:
df = churn.copy()
df

Churn  Tenure  City_Tier  CC_Contacted_LY      Payment  Gender  \
0          1     4.0        3.0              6.0   Debit Card  Female   
1          1     0.0        1.0              8.0          UPI    Male   
2          1     0.0        1.0             30.0   Debit Card    Male   
3          1     0.0        3.0             15.0   Debit Card    Male   
4          1     0.0        1.0             12.0  Credit Card    Male   
...      ...     ...        ...              ...          ...     ...   
11255      0    10.0        1.0             34.0  Credit Card    Male   
11256      0    13.0        1.0             19.0  Credit Card    Male   
11257      0     1.0        1.0             14.0   Debit Card    Male   
11258      0    23.0        3.0             11.0  Credit Card    Male   
11259      0     8.0        1.0             22.0  Credit Card    Male   

       Service_Score  Account_user_count account_segment  CC_Agent_Score  \
0                3.0                   3           Super             2.0   
1                3.0                   4       Regular +             3.0   
2                2.0                   4       Regular +             3.0   
3                2.0                   4           Super             5.0   
4                2.0                   3       Regular +             5.0   
...              ...                 ...             ...             ...   
11255            3.0                   2           Super             1.0   
11256            3.0                   5             HNI             5.0   
11257            3.0                   2           Super             4.0   
11258            4.0                   5           Super             4.0   
11259            3.0                   2           Super             3.0   

      Marital_Status  rev_per_month  Complain_ly  rev_growth_yoy  \
0             Single            9.0          1.0            11.0   
1             Single            7.0          1.0            15.0   
2             Single            6.0          1.0            14.0   
3             Single            8.0          0.0            23.0   
4             Single            3.0          0.0            11.0   
...              ...            ...          ...             ...   
11255        Married            9.0          0.0            19.0   
11256        Married            7.0          0.0            16.0   
11257        Married            7.0          1.0            22.0   
11258        Married            7.0          0.0            16.0   
11259        Married            5.0          0.0            13.0   

       coupon_used_for_payment  Day_Since_CC_connect    cashback Login_device  
0                          1.0                   5.0  159.930000       Mobile  
1                          0.0                   0.0  120.900000       Mobile  
2                          0.0                   3.0  196.227799       Mobile  
3                          0.0                   3.0  134.070000       Mobile  
4                          1.0                   3.0  129.600000       Mobile  
...                        ...                   ...         ...          ...  
11255                      1.0                   4.0  153.710000     Computer  
11256                      1.0                   8.0  226.910000       Mobile  
11257                      1.0                   4.0  191.420000       Mobile  
11258                      2.0                   9.0  179.900000     Computer  
11259                      2.0                   3.0  175.040000       Mobile  

[11260 rows x 18 columns]

### Clustering

#### Data encoding

In [7]:
dfe = pd.get_dummies(df, drop_first =True)
dfe.head()

Churn  Tenure  City_Tier  CC_Contacted_LY  Service_Score  \
0      1     4.0        3.0              6.0            3.0   
1      1     0.0        1.0              8.0            3.0   
2      1     0.0        1.0             30.0            2.0   
3      1     0.0        3.0             15.0            2.0   
4      1     0.0        1.0             12.0            2.0   

   Account_user_count  CC_Agent_Score  rev_per_month  Complain_ly  \
0                   3             2.0            9.0          1.0   
1                   4             3.0            7.0          1.0   
2                   4             3.0            6.0          1.0   
3                   4             5.0            8.0          0.0   
4                   3             5.0            3.0          0.0   

   rev_growth_yoy  ...  Payment_E wallet  Payment_UPI  Gender_Male  \
0            11.0  ...                 0            0            0   
1            15.0  ...                 0            1            1   
2            14.0  ...                 0            0            1   
3            23.0  ...                 0            0            1   
4            11.0  ...                 0            0            1   

   account_segment_Regular  account_segment_Regular +  account_segment_Super  \
0                        0                          0                      1   
1                        0                          1                      0   
2                        0                          1                      0   
3                        0                          0                      1   
4                        0                          1                      0   

   account_segment_Super +  Marital_Status_Married  Marital_Status_Single  \
0                        0                       0                      1   
1                        0                       0                      1   
2                        0                       0                      1   
3                        0                       0                      1   
4                        0                       0                      1   

   Login_device_Mobile  
0                    1  
1                    1  
2                    1  
3                    1  
4                    1  

[5 rows x 25 columns]

#### Data Splitting

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
X = dfe.drop('Churn', axis=1)
y = dfe[['Churn']]

In [10]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.30, random_state=1, stratify=df['Churn'])

In [11]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(7882, 24)
(3378, 24)
(7882, 1)
(3378, 1)


In [12]:
print(X_train.shape[0]/11260*100)
print(X_test.shape[0]/11260*100)
print(y_train.shape[0]/11260*100)
print(y_test.shape[0]/11260*100)

70.0
30.0
70.0
30.0


## 1) CART

In [13]:
from sklearn.tree import DecisionTreeClassifier

In [14]:
cart = DecisionTreeClassifier(criterion = 'gini')

In [15]:
cart.fit(X_train, y_train)

DecisionTreeClassifier()

##### Tree visualization

In [16]:
from sklearn import tree

In [17]:
train_char_label = ['0', '1']

In [20]:
churn_tree_file = open('d:\churn_tree.dot', 'w')

In [21]:
dot_data = tree.export_graphviz(cart, out_file=churn_tree_file, feature_names=list(X_train), class_names=list(train_char_label))

In [22]:
churn_tree_file.close()

##### Model_evaluation

In [23]:
cart.score(X_train, y_train)

1.0

In [24]:
cart.score(X_test, y_test)

0.9476021314387212

In [25]:
y_pred_cart_train = cart.predict(X_train)
y_pred_cart_test = cart.predict(X_test)

In [26]:
from sklearn.metrics import classification_report, confusion_matrix

In [27]:
confusion_matrix(y_train, y_pred_cart_train)

array([[6555,    0],
       [   0, 1327]], dtype=int64)

In [28]:
confusion_matrix(y_test, y_pred_cart_test)

array([[2721,   88],
       [  89,  480]], dtype=int64)

In [29]:
print(classification_report(y_train, y_pred_cart_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6555
           1       1.00      1.00      1.00      1327

    accuracy                           1.00      7882
   macro avg       1.00      1.00      1.00      7882
weighted avg       1.00      1.00      1.00      7882



In [30]:
print(classification_report(y_test, y_pred_cart_test))

              precision    recall  f1-score   support

           0       0.97      0.97      0.97      2809
           1       0.85      0.84      0.84       569

    accuracy                           0.95      3378
   macro avg       0.91      0.91      0.91      3378
weighted avg       0.95      0.95      0.95      3378



## 2) RF

In [20]:
from sklearn.ensemble import RandomForestClassifier

In [21]:
rf = RandomForestClassifier()

In [22]:
rf.fit(X_train, y_train)

C:\Users\Nandha Keshore\AppData\Local\Temp\ipykernel_7124\2725846524.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rf.fit(X_train, y_train)


RandomForestClassifier()

In [23]:
rf.oob_score

False

##### Model_evaluation

In [36]:
rf.score(X_train, y_train)

1.0

In [37]:
rf.score(X_test, y_test)

0.9692125518058022

In [59]:
y_pred_rf_train = rf.predict(X_train)
y_pred_rf_test = rf.predict(X_test)

In [39]:
from sklearn.metrics import classification_report, confusion_matrix

In [60]:
confusion_matrix(y_train, y_pred_rf_train)

array([[6555,    0],
       [   0, 1327]], dtype=int64)

In [61]:
confusion_matrix(y_test, y_pred_rf_test)

array([[2799,   10],
       [  94,  475]], dtype=int64)

In [62]:
print(classification_report(y_train, y_pred_rf_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6555
           1       1.00      1.00      1.00      1327

    accuracy                           1.00      7882
   macro avg       1.00      1.00      1.00      7882
weighted avg       1.00      1.00      1.00      7882



In [63]:
print(classification_report(y_test, y_pred_rf_test))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      2809
           1       0.98      0.83      0.90       569

    accuracy                           0.97      3378
   macro avg       0.97      0.92      0.94      3378
weighted avg       0.97      0.97      0.97      3378



## 3) Logistic

In [44]:
from sklearn.linear_model import LogisticRegression

In [49]:
lor = LogisticRegression(max_iter=1000)

In [50]:
lor.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=1000)

##### Model_evaluation

In [51]:
lor.score(X_train, y_train)

0.8908906368941893

In [48]:
lor.score(X_test, y_test)

0.8801065719360568

In [64]:
y_pred_lor_train = lor.predict(X_train)
y_pred_lor_test = lor.predict(X_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix

In [65]:
confusion_matrix(y_train, y_pred_lor_train)

array([[6359,  196],
       [ 664,  663]], dtype=int64)

In [66]:
confusion_matrix(y_test, y_pred_lor_test)

array([[2731,   78],
       [ 297,  272]], dtype=int64)

In [67]:
print(classification_report(y_train, y_pred_lor_train))

              precision    recall  f1-score   support

           0       0.91      0.97      0.94      6555
           1       0.77      0.50      0.61      1327

    accuracy                           0.89      7882
   macro avg       0.84      0.73      0.77      7882
weighted avg       0.88      0.89      0.88      7882



In [68]:
print(classification_report(y_test, y_pred_lor_test))

              precision    recall  f1-score   support

           0       0.90      0.97      0.94      2809
           1       0.78      0.48      0.59       569

    accuracy                           0.89      3378
   macro avg       0.84      0.73      0.76      3378
weighted avg       0.88      0.89      0.88      3378



## 4) LDA

In [69]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [70]:
lda = LinearDiscriminantAnalysis()

In [71]:
lda.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearDiscriminantAnalysis()

##### Model_evaluation

In [72]:
lda.score(X_train, y_train)

0.8845470692717584

In [73]:
lda.score(X_test, y_test)

0.8854351687388987

In [74]:
y_pred_lda_train = lda.predict(X_train)
y_pred_lda_test = lda.predict(X_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix

In [75]:
confusion_matrix(y_train, y_pred_lda_train)

array([[6357,  198],
       [ 712,  615]], dtype=int64)

In [76]:
confusion_matrix(y_test, y_pred_lda_test)

array([[2735,   74],
       [ 313,  256]], dtype=int64)

In [77]:
print(classification_report(y_train, y_pred_lda_train))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93      6555
           1       0.76      0.46      0.57      1327

    accuracy                           0.88      7882
   macro avg       0.83      0.72      0.75      7882
weighted avg       0.88      0.88      0.87      7882



In [78]:
print(classification_report(y_test, y_pred_lda_test))

              precision    recall  f1-score   support

           0       0.90      0.97      0.93      2809
           1       0.78      0.45      0.57       569

    accuracy                           0.89      3378
   macro avg       0.84      0.71      0.75      3378
weighted avg       0.88      0.89      0.87      3378



## 5) KNN

In [79]:
from sklearn.neighbors import KNeighborsClassifier

In [80]:
knn = KNeighborsClassifier()

In [81]:
knn.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:207: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

##### Model_evaluation

In [82]:
knn.score(X_train, y_train)

0.9199441766049226

In [83]:
knn.score(X_test, y_test)

0.8715216104203671

In [84]:
y_pred_knn_train = knn.predict(X_train)
y_pred_knn_test = knn.predict(X_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix

In [85]:
confusion_matrix(y_train, y_pred_knn_train)

array([[6381,  174],
       [ 457,  870]], dtype=int64)

In [86]:
confusion_matrix(y_test, y_pred_knn_test)

array([[2676,  133],
       [ 301,  268]], dtype=int64)

In [87]:
print(classification_report(y_train, y_pred_knn_train))

              precision    recall  f1-score   support

           0       0.93      0.97      0.95      6555
           1       0.83      0.66      0.73      1327

    accuracy                           0.92      7882
   macro avg       0.88      0.81      0.84      7882
weighted avg       0.92      0.92      0.92      7882



In [88]:
print(classification_report(y_test, y_pred_knn_test))

              precision    recall  f1-score   support

           0       0.90      0.95      0.92      2809
           1       0.67      0.47      0.55       569

    accuracy                           0.87      3378
   macro avg       0.78      0.71      0.74      3378
weighted avg       0.86      0.87      0.86      3378



## 6) ANN

In [37]:
from sklearn.neural_network import MLPClassifier  

In [38]:
from sklearn.preprocessing import StandardScaler

In [39]:
sc = StandardScaler()

In [40]:
X1_train = sc.fit_transform(X_train)

In [43]:
X1_test = sc.transform(X_test)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [44]:
ann = MLPClassifier(hidden_layer_sizes=100,
                    max_iter=5000,
                    solver='sgd', 
                    verbose=True,  
                    random_state=21,
                    tol=0.01)

In [46]:
ann.fit(X1_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:1118: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


Iteration 1, loss = 0.70513628
Iteration 2, loss = 0.50796925
Iteration 3, loss = 0.45071022
Iteration 4, loss = 0.42575216
Iteration 5, loss = 0.40989829
Iteration 6, loss = 0.39779315
Iteration 7, loss = 0.38777547
Iteration 8, loss = 0.37924123
Iteration 9, loss = 0.37188797
Iteration 10, loss = 0.36543868
Iteration 11, loss = 0.35968923
Iteration 12, loss = 0.35461801
Iteration 13, loss = 0.35003536
Iteration 14, loss = 0.34590404
Iteration 15, loss = 0.34215816
Iteration 16, loss = 0.33873000
Iteration 17, loss = 0.33558041
Iteration 18, loss = 0.33272582
Training loss did not improve more than tol=0.010000 for 10 consecutive epochs. Stopping.


MLPClassifier(hidden_layer_sizes=100, max_iter=5000, random_state=21,
              solver='sgd', tol=0.01, verbose=True)

##### Model_evaluation

In [47]:
ann.score(X1_train, y_train)

0.86513575234712

In [48]:
ann.score(X1_test, y_test)

0.8315571343990527

In [50]:
y_pred_ann_train = ann.predict(X1_train)
y_pred_ann_test = ann.predict(X1_test)

In [53]:
from sklearn.metrics import classification_report, confusion_matrix

In [51]:
confusion_matrix(y_train, y_pred_ann_train)

array([[6473,   82],
       [ 981,  346]], dtype=int64)

In [55]:
confusion_matrix(y_test, y_pred_ann_test)

array([[2809,    0],
       [ 569,    0]], dtype=int64)

In [53]:
print(classification_report(y_train, y_pred_ann_train))

              precision    recall  f1-score   support

           0       0.87      0.99      0.92      6555
           1       0.81      0.26      0.39      1327

    accuracy                           0.87      7882
   macro avg       0.84      0.62      0.66      7882
weighted avg       0.86      0.87      0.83      7882



In [54]:
print(classification_report(y_test, y_pred_ann_test))

              precision    recall  f1-score   support

           0       0.83      1.00      0.91      2809
           1       0.00      0.00      0.00       569

    accuracy                           0.83      3378
   macro avg       0.42      0.50      0.45      3378
weighted avg       0.69      0.83      0.76      3378



C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1334: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


## Ensemble modelling

## 1) Bagging

In [18]:
from sklearn.ensemble import BaggingClassifier

In [25]:
bag = BaggingClassifier(base_estimator = rf, random_state= 1)

In [26]:
bag.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\ensemble\_bagging.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


BaggingClassifier(base_estimator=RandomForestClassifier(), random_state=1)

##### Model_evaluation

In [27]:
bag.score(X_train, y_train)

0.9954326313118498

In [28]:
bag.score(X_test, y_test)

0.9603315571343991

In [29]:
y_pred_bag_train = bag.predict(X_train)
y_pred_bag_test = bag.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

In [31]:
confusion_matrix(y_train, y_pred_bag_train)

array([[6555,    0],
       [  36, 1291]], dtype=int64)

In [32]:
confusion_matrix(y_test, y_pred_bag_test)

array([[2803,    6],
       [ 128,  441]], dtype=int64)

In [33]:
print(classification_report(y_train, y_pred_bag_train))

              precision    recall  f1-score   support

           0       0.99      1.00      1.00      6555
           1       1.00      0.97      0.99      1327

    accuracy                           1.00      7882
   macro avg       1.00      0.99      0.99      7882
weighted avg       1.00      1.00      1.00      7882



In [34]:
print(classification_report(y_test, y_pred_bag_test))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98      2809
           1       0.99      0.78      0.87       569

    accuracy                           0.96      3378
   macro avg       0.97      0.89      0.92      3378
weighted avg       0.96      0.96      0.96      3378



## 2) Adaboost

In [35]:
from sklearn.ensemble import AdaBoostClassifier

In [36]:
aboost = AdaBoostClassifier(base_estimator = rf, random_state= 1)

In [37]:
aboost.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


AdaBoostClassifier(base_estimator=RandomForestClassifier(), random_state=1)

##### Model_evaluation

In [38]:
aboost.score(X_train, y_train)

1.0

In [39]:
aboost.score(X_test, y_test)

0.9706927175843695

In [40]:
y_pred_aboost_train = aboost.predict(X_train)
y_pred_aboost_test = aboost.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

In [41]:
confusion_matrix(y_train, y_pred_aboost_train)

array([[6555,    0],
       [   0, 1327]], dtype=int64)

In [42]:
confusion_matrix(y_test, y_pred_aboost_test)

array([[2801,    8],
       [  91,  478]], dtype=int64)

In [43]:
print(classification_report(y_train, y_pred_aboost_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6555
           1       1.00      1.00      1.00      1327

    accuracy                           1.00      7882
   macro avg       1.00      1.00      1.00      7882
weighted avg       1.00      1.00      1.00      7882



In [44]:
print(classification_report(y_test, y_pred_aboost_test))

              precision    recall  f1-score   support

           0       0.97      1.00      0.98      2809
           1       0.98      0.84      0.91       569

    accuracy                           0.97      3378
   macro avg       0.98      0.92      0.94      3378
weighted avg       0.97      0.97      0.97      3378



## 3) Gradientboost

In [46]:
from sklearn.ensemble import GradientBoostingClassifier

In [48]:
gboost = GradientBoostingClassifier(random_state= 1)

In [49]:
gboost.fit(X_train, y_train)

C:\Users\Nandha Keshore\anaconda3\lib\site-packages\sklearn\ensemble\_gb.py:570: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


GradientBoostingClassifier(random_state=1)

##### Model_evaluation

In [50]:
gboost.score(X_train, y_train)

0.922481603653895

In [51]:
gboost.score(X_test, y_test)

0.9103019538188277

In [52]:
y_pred_gboost_train = gboost.predict(X_train)
y_pred_gboost_test = gboost.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

In [53]:
confusion_matrix(y_train, y_pred_gboost_train)

array([[6406,  149],
       [ 462,  865]], dtype=int64)

In [54]:
confusion_matrix(y_test, y_pred_gboost_test)

array([[2738,   71],
       [ 232,  337]], dtype=int64)

In [55]:
print(classification_report(y_train, y_pred_gboost_train))

              precision    recall  f1-score   support

           0       0.93      0.98      0.95      6555
           1       0.85      0.65      0.74      1327

    accuracy                           0.92      7882
   macro avg       0.89      0.81      0.85      7882
weighted avg       0.92      0.92      0.92      7882



In [56]:
print(classification_report(y_test, y_pred_gboost_test))

              precision    recall  f1-score   support

           0       0.92      0.97      0.95      2809
           1       0.83      0.59      0.69       569

    accuracy                           0.91      3378
   macro avg       0.87      0.78      0.82      3378
weighted avg       0.91      0.91      0.90      3378



## 4) Xboost

In [63]:
pip install xgboost

In [65]:
import xgboost as xgb

In [66]:
xboost = xgb.XGBClassifier(random_state=1,learning_rate=0.01)

In [67]:
xboost.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, gpu_id=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=0.01, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              n_estimators=100, n_jobs=None, num_parallel_tree=None,
              predictor=None, random_state=1, ...)

##### Model_evaluation

In [69]:
xboost.score(X_train, y_train)

0.9218472468916519

In [70]:
xboost.score(X_test, y_test)

0.9088217880402605

In [71]:
y_pred_xboost_train = xboost.predict(X_train)
y_pred_xboost_test = xboost.predict(X_test)

In [30]:
from sklearn.metrics import classification_report, confusion_matrix

In [72]:
confusion_matrix(y_train, y_pred_xboost_train)

array([[6366,  189],
       [ 427,  900]], dtype=int64)

In [73]:
confusion_matrix(y_test, y_pred_xboost_test)

array([[2722,   87],
       [ 221,  348]], dtype=int64)

In [74]:
print(classification_report(y_train, y_pred_xboost_train))

              precision    recall  f1-score   support

           0       0.94      0.97      0.95      6555
           1       0.83      0.68      0.75      1327

    accuracy                           0.92      7882
   macro avg       0.88      0.82      0.85      7882
weighted avg       0.92      0.92      0.92      7882



In [75]:
print(classification_report(y_test, y_pred_xboost_test))

              precision    recall  f1-score   support

           0       0.92      0.97      0.95      2809
           1       0.80      0.61      0.69       569

    accuracy                           0.91      3378
   macro avg       0.86      0.79      0.82      3378
weighted avg       0.90      0.91      0.90      3378



## Model tuning

### 1) CART

In [1]:
cart_reg = DecisionTreeClassifier(criterion = 'gini', max_depth=10, min_samples_leaf = 20, min_samples_split= 50)

NameError: name 'DecisionTreeClassifier' is not defined

In [60]:
cart_reg.fit(X_train, y_train)

DecisionTreeClassifier(max_depth=10, min_samples_leaf=20, min_samples_split=50)

##### Regularised Model evaluation

In [61]:
cart_reg.score(X_train, y_train)

0.915503679269221

In [62]:
cart_reg.score(X_test, y_test)

0.9088217880402605